export const UPDATE_NOTIFICATION_LIST = 'UPDATE_NOTIFICATION_LIST';
export const UPDATE_PREVIOUS_NOTIFICATION_LIST =
  'UPDATE_PREVIOUS_NOTIFICATION_LIST';
export const UPDATE_CHECKED_AMOUNT = 'UPDATE_CHECKED_AMOUNT';
